SELECT * FROM EVENT;
SELECT * FROM CUSTOMER;
SELECT * FROM OWNER;
SELECT * FROM MENU;
SELECT * FROM SALES;
SELECT * FROM REVIEW;
SELECT * FROM FOODTRUCK;
SELECT * FROM TYPE;

alter table CUSTOMER modify c_bdate date default sysdate;

SELECT * FROM FOODTRUCK

WHERE F_NUM = 45


SELECT * FROM MENU
WHERE F_NUM = 5